/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface PortfolioItem {
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
}
export interface Testimonial {
  'review' : string,
  'clientName' : string,
  'role' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addPortfolioItem' : ActorMethod<
    [string, string, Category, string],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, string, string, bigint], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPortfolioByCategory' : ActorMethod<[Category], Array<PortfolioItem>>,
  'submitInquiry' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];